from .tasks.hcaptcha import HCaptchaTask
from .tasks.funcaptcha import FunCaptchaTask
from .tasks.geetest import GeeTestTask
from .tasks.recaptchav2 import ReCaptchaV2Task
from .tasks.recaptchav3 import ReCaptchaV3Task
from .tasks.mtcaptcha import MtCaptchaTask
from .tasks.datadome import DatadomeTask
from .tasks.cloudflare_turnstile import CloudflareTurnstileTask
from .tasks.cloudflare_challenge import CloudflareChallengeTask
from .recognitions.image_to_task import ImageToTextTask
from .recognitions.hcaptcha import HCaptchaClassification
from .recognitions.funcaptcha import FunCaptchaClassification
from .recognitions.recaptcha import ReCaptchaClassification
from .recognitions.aws_waf import AwsWafClassification
